CREATE TABLE IF NOT EXISTS calculation_history (
    id INT PRIMARY KEY AUTO_INCREMENT,
    expression VARCHAR(255) NOT NULL,
    result VARCHAR(255) NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
